Avoid typeerror exception on tests
when running with pytest 8.3.3 on python 3.13 tests fail with

  TypeError: exceptions must be derived from Warning, not <class 'NoneType'>

turns out the way to check that no warnings are emitted is not
warns(None).